# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AI Sex hormone Test
email: face.hormone@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  얼굴 빅데이터로 분석하는 성호르몬 테스트는 사람의 얼굴, 체형, 심지어 뇌의 발달과 성격 형성에도 결정적인 영향을 주고 있는 성호르몬의 유형을 AI를 통해 학습한 결과를 제공해 드립니다. 나는 어떤 성호르몬 유형을 갖고 있을까요? 나의 성호르몬 유형 분석을 해보세요! 수많은 얼굴사진 데이터를 기반으로 학습한 인공지능이 나의 얼굴 사진을 통해 성호르몬 유형을 찾아드립니다.본 서비스는 Google의 인공지능 teachable machine 2.0을 활용하였습니다.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://sexhormone.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sexhormone1
github_username:  sexhormone

# Build settings
theme: minima
plugins:
 # - jekyll-polyglot
  - jekyll-feed
  - jekyll-admin
  - jekyll-sitemap

#languages: ['ja', 'ko', 'en', 'cn']
#default_lang: 'ko'
#exclude_from_localization: ['javascript', 'images', 'css']
#parallel_localization: false
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
